matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services:
        - xvfb
      before_install:
        - sudo apt-get install -y xclip;
      script:
        - export FrameworkPathOverride=/usr/lib/mono/4.7.2-api/
    - os: osx
      sudo: required
      script:
        - export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/4.7.2-api/
language: csharp
mono: latest
dotnet: 3.1.100
script:
  - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
  - dotnet build src --configuration Release
  - dotnet test src/Tests/Tests.csproj --configuration Release --framework netcoreapp3.1 --no-build --no-restore
  - mono ./testrunner/xunit.runner.console.2.4.1/tools/net472/xunit.console.exe ./src/Tests/bin/Release/net472/Tests.dll