os:
  - linux
  - osx
sudo: required
language: csharp
before_install:
 - if [ "$os" == "linux" ]; then sudo apt-get install -y xclip
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
mono: none
dotnet: 2.1.400
script:
 - dotnet restore
 - dotnet build
 - dotnet test Tests/Tests.csproj --no-build